version: 2.1

executors:
  base-executor:
    docker:
      - image: cimg/base:current

jobs:
  build:
    executor: base-executor
    working_directory: ~/project
    steps:
      - checkout

      # Set up dependencies
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk ruby-full
            gem install bundler fastlane

      # Decode sensitive files
      - run:
          name: Decode Keystore
          command: |
            echo $KEYSTORE_BASE64 | base64 --decode > android/app/my-release-key.jks
      - run:
          name: Decode Google Services
          command: |
            echo $GOOGLE_SERVICES_JSON | base64 --decode > android/app/google-services.json

      # Build APK
      - run:
          name: Build APK
          command: ./gradlew assembleRelease -Pandroid.injected.signing.store.file=android/app/my-release-key.jks \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD

      # Deploy using Fastlane
      - run:
          name: Deploy to Google Play
          command: bundle exec fastlane deploy

      # Cleanup sensitive files
      - run:
          name: Cleanup sensitive files
          command: |
            rm android/app/my-release-key.jks
            rm android/app/google-services.json

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
