version: 2.1

executors:
  android-flutter:
    docker:
      - image: gmemstr/flutter-fastlane:latest
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

jobs:
  alpha_deploy:
    executor: android-flutter
    steps:

      # Checkout source code
      - checkout

      - run:
          name: Debug Keystore Variable
          command: echo "$KEYSTORE_BASE64" | head -c 100


      # Decode the keystore from Base64
      - run:
          name: Decode Keystore
          command: echo "$KEYSTORE_BASE64" | tr -d '\n' | base64 --decode > android/app/my-release-key.jks

      # Decode Google Services JSON
      - run:
          name: Decode Google Services JSON
          command: echo "$GOOGLE_SERVICES_JSON" | tr -d '\n' | base64 --decode > android/app/google-services.json

      # Decode Google Play Service Account JSON
      - run:
          name: Decode Google Play Service Account JSON
          command: echo "$GOOGLE_PLAY_JSON" | tr -d '\n' | base64 --decode > android/google-play-service-account.json

      # Run Fastlane for alpha release
      - run:
          name: Fastlane Alpha Deployment
          command: cd android && fastlane alpha

      # Cleanup sensitive files
      - run:
          name: Cleanup Sensitive Files
          command: |
            rm android/app/my-release-key.jks
            rm android/app/google-services.json
            rm android/google-play-service-account.json

workflows:
  deploy:
    jobs:
      - alpha_deploy:
          filters:
            branches:
              only: main
