# This Fastfile contains the configuration for deploying your app using Fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build and Deploy to Google Play (Closed Testing)"
  lane :alpha do
    # Build the APK
    gradle(task: "clean assembleRelease", project_dir: 'android/')  
    # Upload to Google Play
    upload_to_play_store(
      json_key: "android/google-play-service-account.json", # Path to the decoded JSON key
      track: "alpha", # Alpha track for testing
      apk: "./app/build/outputs/apk/release/app-release.apk" # Path to the built APK
    )
  end
  
end
